version: '3.8'

services:

  mysql_symfony:
    container_name: mysql_symfony
    build:
      context: ./docker/mysql
    environment:
      MYSQL_ROOT_PASSWORD: shopping-api
      MYSQL_DATABASE: shopping-api
      MYSQL_USER: shopping-api
      MYSQL_PASSWORD: shopping-api
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - "3305:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - docker_symfony_net_api

  nginx_symfony:
    container_name: nginx_symfony
    build:
      context: ./docker/nginx
    ports:
      - '8080:80'
    volumes:
      - ./app/public:/var/www/shopping-api/public
    networks:
      - docker_symfony_net_api

  php:
    build:
      context: ./docker/php
    volumes:
      - ./app:/var/www/shopping-api
    networks:
      - docker_symfony_net_api

volumes:
  mysql-data:

networks:
  docker_symfony_net_api:
    external: true
