App\Domain\Cart\Cart:
    type: entity
    table: carts
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        buyer_id:
            type: integer
        status:
            type: string
    oneToMany:
        cartProducts:
            targetEntity: App\Domain\CartProduct\CartProduct
            mappedBy: cart
