App\Domain\CartProduct\CartProduct:
    type: entity
    table: cart_products
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        quantity:
            type: integer
    manyToOne:
        cart:
            targetEntity: App\Domain\Cart\Cart
            inversedBy: cartProducts
            joinColumn:
                name: cart_id
                referencedColumnName: id
        product:
            targetEntity: App\Domain\Product\Product
            joinColumn:
                name: product_id
                referencedColumnName: id