doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'

        profiling_collect_backtrace: '%kernel.debug%'
        types:
            product_name: App\Infrastructure\Doctrine\Orm\Types\ProductNameType
            product_price: App\Infrastructure\Doctrine\Orm\Types\ProductPriceType
            buyer_name: App\Infrastructure\Doctrine\Orm\Types\BuyerNameType
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/src/Infrastructure/Doctrine/Orm'
                prefix: 'App\Domain'
                alias: App